-- AlterTable
ALTER TABLE "BudgetDetails" ALTER COLUMN "estimated" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "remaining" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "spent" SET DATA TYPE DECIMAL(65,30);
